name: Run flake8 and Unit Tests
on: push
jobs:
  execute_tests:
    name: Prepare and Run flake8, and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run flake8 and execute unit tests
        env:
          DJANGO_SETTINGS_MODULE: learnwebdev.settings
        run: flake8 && python manage.py test